### ISSUE TITLE
db.Get panics for non-existent ID

### ISSUE THREAD

**Issue by tomsteele** [nlf/boltons#2]
not sure if the intention was to call db.Exists before calling db.Get. Can Get check for a nil and return an error? hmmm not sure I like that actually, db.Exists may just be better. What was your thought?

**Comment by nlf** [comment]
hadn't really thought about it, might be best to have db.Get return an error if the key doesn't exist.. it definitely shouldn't panic though

**Comment by tomsteele** [comment]
How db libs handle a not found is a question as old as time :)
